Add chunked-upload and support for audio/video processing
tony612/qiniu pull request #12
Opened 2017-07-18 03:37 UTC by beams0305

[Qiniu Chunked-Upload](https://developer.qiniu.com/kodo/manual/1650/chunked-upload)
[Qiniu AV Processing](https://developer.qiniu.com/dora/manual/3685/directions-for-use-av)

2017-07-18 14:08 UTC, tony612 requested changes

2017-07-18 14:08 UTC, tony612 commented on lib/qiniu/chunk_upload.ex
> +        |> Stream.map(fn(blk) ->
How about extract this anonymous function to a function in a module?

2017-07-18 14:08 UTC, tony612 commented on lib/qiniu/chunk_upload.ex
> +
I prefer to delete this blank line for this kind of function.

2017-07-18 14:08 UTC, tony612 commented on lib/qiniu/fop/av.ex
> +    query_opts = opts |> Keyword.take([:"notifyURL", :pipeline]) |> Enum.into(%{})
Why not use `: notifyURL` directly? And the one on next line.

2017-07-18 14:08 UTC, tony612 commented on lib/qiniu/fop/av.ex
> +    )
It seems that it can be changed to?
```
%{...}
|> Map.merge(query_opts)
|> URI.encode_query
```

2017-07-19 02:56 UTC, xingxing commented on lib/qiniu/chunk_upload.ex
> +        |> Stream.map(fn(blk) ->
I think that anonymous function is  explicit enough:  `A block |> chop  |> upload`

2017-07-19 04:55 UTC, merged

2017-07-19 05:00 UTC, tony612 commented
merged. And 0.4.0 is published with this feature. Thank you!